version: '3.9'

services: 
  postgres: # define as propriedades do postgres
    image: postgres:latest
    container_name: postgres-etl
    env_file:
      - ./config/postgre.env
    ports:
      - 5432:5432  
    networks:
      - fzin_network  

  mongodb: # define as propriedades de mongoDB
    image: mongo:latest
    container_name: mongodb_container
    env_file:
      - ./config/mongo.env
    ports:
      - 27017:27017    
    volumes:
      - ./mongodb-init/init.js:/docker-entrypoint-initdb.d/init.js:ro
    networks:
      - fzin_network  

  python_app: # define as propriedades do python
    build:
      context: ./python_etl
      dockerfile: /docker/Dockerfile
    container_name: python_app
    depends_on:
      - mongodb
      - postgres
    volumes:
      - ./python_etl:/app
    networks:
      - fzin_network   

networks: #define a rede
  fzin_network:
